export type Mode='MOCK'|'LIVE'|'CACHED'|'STALE'|'UNAVAILABLE';
export interface Location {latitude:number;longitude:number}
export interface Profile {id:string;full_name:string;email:string;role:'citizen'|'officer'|'admin';officer_verified:boolean;officer_requested:boolean;preferred_language:string}
export interface Provenance {source:string;data_mode:Mode|string;updated_at:string;created_at:string}
export interface Zone extends Location,Provenance {id:string;name:string;district:string;state:string;risk_score:number;risk_level:string;radius_m:number;estimated_population:number;features:Record<string,number>;contributing_factors:string[];distance_m:number}
export interface Incident extends Location,Provenance {id:string;type:string;description:string;severity:string;status:string;confirmation_count:number;community_confidence_score:number;verification_notes?:string}
export interface History extends Location,Provenance {id:string;event_date:string;district:string;state:string;severity:string}
export interface Shelter extends Location,Provenance {id:string;name:string;capacity:number;current_occupancy:number;available_capacity:number;contact:string;district:string;state:string;verified:boolean;active:boolean;distance_m:number}
export interface Road extends Location,Provenance {id:string;road_identifier:string;status:string;risk_score:number}
export interface Route extends Provenance {id:string;name:string;coordinates:[number,number][];distance_m:number;duration_seconds:number;route_risk_score:number;excluded:boolean;classification:string;coverage:number;reasons:string[];notice:string;travel_advice?:string}
export interface Notification {id:string;incident_id:string|null;title:string;message:string;severity:string;read:boolean;type:string;created_at:string}
export interface ForecastWindow {start:string;end:string;hours:number;precipitation_mm:number|null;precipitation_probability_pct:number|null;rain_level:string}
export interface Weather extends Provenance {rainfall_1h:number|null;rainfall_24h:number|null;rainfall_72h:number|null;humidity:number|null;temperature:number|null;weather_code?:number|null;soil_moisture_pct?:number|null;weather_location?:string;rainfall_trend:string;observation_time:string;forecast_windows?:ForecastWindow[];satellite_rainfall_24h?:number|null;satellite_source?:string;satellite_latency_note?:string}
export interface RegionalHazard extends Partial<Provenance>,Location {id:string;hazard_type:string;severity:string;title:string;message:string;region?:string;country?:string;affected_regions:string[];rainfall_24h_mm:number|null;forecast_rain_mm:number|null;confidence:string;verified:boolean;observed_at?:string;expires_at?:string}
export interface LiveRisk extends Partial<Provenance> {risk_score:number|null;risk_level:string;severity:string;landslide_score?:number|null;landslide_level?:string;flood_score?:number|null;flood_level?:string;data_quality_pct?:number;guidance:string;contributing_factors:string[];missing_features:string[];nearby_active_incidents:number;nearby_history_count:number;historical_source?:string;coverage_note:string;weather:Weather|null;terrain?:{elevation_m?:number|null;slope_deg?:number|null;local_relief_m?:number|null;source?:string;data_mode?:string;method_note?:string}|null;flood_context?:{current_discharge_m3s?:number|null;baseline_30d_median_m3s?:number|null;forecast_7d_max_m3s?:number|null;relative_discharge_ratio?:number|null;forecast_ratio?:number|null;flood_signal_score?:number|null;source?:string;data_mode?:string;coverage_note?:string}|null;ml?:{available:boolean;probability:number|null;model_status:string}|null;regional_alerts:RegionalHazard[]}
export interface SOSEvent extends Location,Partial<Provenance> {id:string;user_id:string;emergency_type:string;message:string;status:string;created_at:string;assigned_officer_id?:string|null;nearest_resources?:EmergencyResource[]}
export interface EmergencyResource extends Location,Partial<Provenance> {id?:string;name:string;type:string;phone?:string;distance_m?:number;verified?:boolean}
export interface Overview extends Provenance {critical_zones:number;active_incidents:number;awaiting_verification:number;road_blockages:number;population_at_risk:number;available_shelters:number;incident_queue:Incident[]}
export interface Exposure extends Zone {estimated_exposed_population:number;exposure_priority_score:number;verified_shelters_nearby:number;road_accessibility:string}
export interface Dispatch {id:string;incident_id:string;assigned_team:string;priority:string;status:string;instructions:string;created_at:string}
export type Page='overview'|'incidents'|'routes'|'history'|'alerts'|'shelters'|'officer'|'population'|'dispatches'|'settings';

export interface IntelligenceLead extends Location,Partial<Provenance> {area:string;hazard:string;severity:string;confidence:string;corroboration_score:number;evidence_count:number;independent_sources:number;rainfall_24h_mm:number;affected_areas:string[];impact_window:string;recommended_action:string;analysis_note:string;evidence:{source:string;source_type:string;title:string;summary:string;url:string;published_at:string}[]}
