import {useEffect,useState} from 'react';
import {MapPin,Upload,CheckCircle2,Navigation,ShieldCheck,Route as RouteIcon} from 'lucide-react';
import {api,post,setToken,supabase,mediaUrl} from './api';
import {queueReport,syncReports,queued} from './offline';
import type {Dispatch,Exposure,Incident,Location,Profile,Route,Shelter,Zone} from './types';
import {Badge,Busy,Coordinates,Empty,ErrorText,getGPS,message,Modal,Source} from './components';
import {RiskMap} from './Map';
export const incidentTypes=['Landslide','Slope crack','Road blockage','Flash flood','Heavy rainfall','Falling rocks','Other'];

export function LoginModal({mode,onClose,onLogin}:{mode:string;onClose:()=>void;onLogin:()=>Promise<void>}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[signup,setSignup]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function submit(e?:React.FormEvent,demoRole?:string){e?.preventDefault();setError('');setBusy(true);try{
  const body={email:demoRole?`${demoRole}@risksetu.demo`:email,password:demoRole?'RiskSetuDemo!2026':password};
  const result=await post<{access_token?:string;refresh_token?:string;message?:string}>(signup?'/api/auth/signup':'/api/auth/login',signup?{...body,full_name:name}:body);
  if(result.access_token){setToken(result.access_token);if(supabase&&result.refresh_token)await supabase.auth.setSession({access_token:result.access_token,refresh_token:result.refresh_token});await onLogin();onClose()}else setNotice(result.message||'Check your email.');
 }catch(e){setError(message(e))}finally{setBusy(false)}}
 return <Modal title={signup?'Join RiskSetu':'Welcome to RiskSetu'} onClose={onClose}><p className="muted">Report hazards, receive nearby alerts and help your community stay informed.</p><form onSubmit={submit}>
  {signup&&<label>Full name<input required minLength={2} value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label>}
  <label>Email address<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Password<input required type="password" minLength={signup?10:1} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={signup?'new-password':'current-password'}/></label>
  <ErrorText error={error}/>{notice&&<p className="success-text">{notice}</p>}<button disabled={busy} className="primary wide"><Busy busy={busy}>{signup?'Create citizen account':'Sign in'}</Busy></button></form>
  <button className="text-button wide" onClick={()=>{setSignup(!signup);setError('')}}>{signup?'Already registered? Sign in':'New here? Create an account'}</button>
  {mode==='MOCK'&&!signup&&<div className="demo-login"><p>EXPLORE THE DEMO</p><div className="button-row"><button disabled={busy} onClick={()=>void submit(undefined,'citizen')}>Citizen</button><button disabled={busy} onClick={()=>void submit(undefined,'officer')}>Officer</button><button disabled={busy} onClick={()=>void submit(undefined,'admin')}>Admin</button></div><button className="primary wide demo-showcase" disabled={busy} onClick={()=>{localStorage.setItem('risksetu-demo-tour','1');void submit(undefined,'admin')}}>▶ Demo</button><small>Citizen / Officer / Admin are isolated demo accounts. Demo signs in as demo admin and starts the complete guided RiskSetu showcase. No real authority access.</small></div>}
 </Modal>
}

export function ReportModal({location,user,onClose,onSaved}:{location:Location;user:Profile;onClose:()=>void;onSaved:()=>void}){
 const [coords,setCoords]=useState(location),[type,setType]=useState('Landslide'),[description,setDescription]=useState(''),[severity,setSeverity]=useState('MODERATE'),[file,setFile]=useState<File>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{
  if(file&&file.size>5242880)throw new Error('Choose a file smaller than 5 MB');
  const id=crypto.randomUUID();await queueReport({id,userId:user.id,body:{...coords,type,description,severity,client_id:id},file,createdAt:new Date().toISOString()});
  if(navigator.onLine)await syncReports(user.id);
  const pending=(await queued(user.id)).find(r=>r.id===id);
  setSaved(pending?pending.error?`Saved on this device. Sync needs attention: ${pending.error}`:'Saved offline. It will sync when you are connected.':'Your report was submitted for verification.');onSaved();
 }catch(e){setError(message(e))}finally{setBusy(false)}}
 return <Modal title="Report an incident" onClose={onClose}>{saved?<div className="saved"><CheckCircle2 size={40}/><h3>Report saved</h3><p>{saved}</p><button className="primary" onClick={onClose}>Done</button></div>:<form onSubmit={submit}><p className="muted">Report from a safe location. Do not approach a hazard to collect evidence.</p>
  <div className="form-grid"><label>Incident type<select value={type} onChange={e=>setType(e.target.value)}>{incidentTypes.map(t=><option key={t}>{t}</option>)}</select></label><label>Observed severity<select value={severity} onChange={e=>setSeverity(e.target.value)}>{['LOW','MODERATE','HIGH','CRITICAL'].map(t=><option key={t}>{t}</option>)}</select></label></div>
  <Coordinates value={coords} onChange={setCoords}/><button type="button" className="text-button" onClick={()=>getGPS().then(setCoords).catch(e=>setError(message(e)))}><MapPin size={16}/>Use my GPS location</button>
  <label>What did you observe?<textarea required minLength={8} maxLength={3000} rows={4} placeholder="Describe what happened, nearby landmarks and road conditions…" value={description} onChange={e=>setDescription(e.target.value)}/></label>
  <label className="upload"><Upload size={22}/><span>{file?.name||'Add a photo or short video'}<small>JPG, PNG, WebP or MP4 · up to 5 MB</small></span><input type="file" accept="image/jpeg,image/png,image/webp,video/mp4" onChange={e=>setFile(e.target.files?.[0])}/></label>
  <ErrorText error={error}/><button className="primary wide" disabled={busy}><Busy busy={busy}>Submit report</Busy></button>
 </form>}</Modal>
}

export function IncidentModal({incident,user,onClose,onChanged}:{incident:Incident;user:Profile|null;onClose:()=>void;onChanged:()=>void}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[note,setNote]=useState(''),[team,setTeam]=useState(''),[result,setResult]=useState(''),[summary,setSummary]=useState<{summary:string;actions:string[];source:string;data_mode:'MOCK'|'LIVE'|'CACHED'}|null>(null),[media,setMedia]=useState<{id:string;media_type:string;url?:string;ai_analysis?:{recommended_verification?:string}}[]>([]),[inspection,setInspection]=useState<any>(null);
 const isOfficer=!!user?.officer_verified&&['officer','admin'].includes(user.role);
 async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setError('');try{await action();setResult(success);onChanged()}catch(e){setError(message(e))}finally{setBusy(false)}}
 async function loadEvidence(){const data=await api<{items:typeof media}>(`/api/incidents/${incident.id}/media`);const rows=await Promise.all(data.items.map(async m=>({...m,url:await mediaUrl(m.id)})));setMedia(rows)}
 useEffect(()=>()=>{media.forEach(m=>{if(m.url?.startsWith('blob:'))URL.revokeObjectURL(m.url)})},[media]);
 return <Modal title={incident.type} onClose={onClose}><div className="button-row"><Badge value={incident.severity}/><Badge value={incident.status}/></div><p>{incident.description}</p><p className="muted">{incident.latitude.toFixed(5)}, {incident.longitude.toFixed(5)} · {new Date(incident.created_at).toLocaleString()}</p><Source item={incident}/>
 <div className="confirmation-summary"><strong>{incident.confirmation_count}</strong> confirmations <span>Community confidence {Math.round(incident.community_confidence_score*100)}%</span></div><small className="muted">Community confidence is a triage signal, not scientific verification.</small>
 {user&&['PENDING','COMMUNITY_CONFIRMED'].includes(incident.status)&&<div className="subsection"><h3>Can you confirm this report?</h3><p className="muted">Uses your current GPS location. Available within 1 km. Respond only to what you can safely observe.</p><div className="button-row">{['YES','NO','UNSURE'].map(answer=><button disabled={busy} key={answer} onClick={()=>void run(async()=>post(`/api/incidents/${incident.id}/confirm`,{...await getGPS(),confirmation:answer}),'Your response was recorded.')}>{answer==='YES'?'I can confirm':answer==='NO'?'I do not see it':'Unsure'}</button>)}</div></div>}
 {isOfficer&&<div className="subsection"><h3><ShieldCheck size={18}/>Officer response</h3><label>Verification notes / response instructions<textarea minLength={5} value={note} rows={3} onChange={e=>setNote(e.target.value)} placeholder="Record evidence, field findings and response considerations"/></label><div className="button-row">{['VERIFIED','REJECTED','RESOLVED'].map(status=><button disabled={busy||note.trim().length<5} key={status} onClick={()=>void run(()=>post(`/api/incidents/${incident.id}/verify`,{status,notes:note}),`Status updated to ${status}.`)}>{status==='VERIFIED'?'Verify':status==='REJECTED'?'Reject':'Resolve'}</button>)}</div><label>Response team<input value={team} onChange={e=>setTeam(e.target.value)} placeholder="Team name or identifier"/></label><button disabled={busy||team.length<2||note.length<5} onClick={()=>void run(()=>post(`/api/incidents/${incident.id}/dispatch`,{assigned_team:team,priority:incident.severity,instructions:note}),'Dispatch recorded. Contact the team through your approved channel.')}>Record dispatch</button><div className="button-row"><button disabled={busy} onClick={()=>void run(async()=>setSummary(await api(`/api/incidents/${incident.id}/briefing`)),'')}>Generate incident briefing</button><button disabled={busy} onClick={()=>void run(loadEvidence,'Evidence loaded.')}>Review uploaded evidence</button><button disabled={busy} onClick={()=>void run(async()=>setInspection(await api(`/api/incidents/${incident.id}/inspection`)),'Inspection routes loaded.')}>Incident inspection & hospitals</button></div></div>}
 {inspection&&<div className="briefing inspection"><h3>Incident inspection · emergency access</h3><p>{inspection.note}</p>{inspection.hospitals?.map((h:any)=><div className="inspection-hospital" key={h.id}><strong>{h.name}</strong><p>{h.distance_m?Math.round(h.distance_m/100)/10+' km away':''} · {h.phone||'No phone listed'}</p>{h.routes?.length?<div>{h.routes.map((r:any)=><div className="inspection-route" key={r.id}><Badge value={r.classification}/><span>{(r.distance_m/1000).toFixed(1)} km · {Math.round(r.duration_seconds/60)} min · risk {r.route_risk_score}/100</span><small>{r.travel_advice}</small></div>)}</div>:<p>No assessed route available.</p>}</div>)}</div>}
 {summary&&<div className="briefing"><h3>Incident briefing</h3><p>{summary.summary}</p><ul>{summary.actions.map(a=><li key={a}>{a}</li>)}</ul><Source item={summary}/></div>}
 {media.map(m=><div className="evidence" key={m.id}>{m.media_type.startsWith('image')?<img src={m.url} alt="Submitted incident evidence"/>:<video src={m.url} controls/>}<p>{m.ai_analysis?.recommended_verification}</p></div>)}
 {result&&<p className="success-text" role="status">{result}</p>}<ErrorText error={error}/>
 </Modal>
}

export function RoutesView({location,zones,incidents,user,login}:{location:Location;zones:Zone[];incidents:Incident[];user:Profile|null;login:()=>void}){
 const [destination,setDestination]=useState<Location>({latitude:25.62,longitude:91.89}),[routes,setRoutes]=useState<Route[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function calculate(e:React.FormEvent){e.preventDefault();if(!user)return login();setBusy(true);setError('');try{const data=await post<{routes:Route[];message:string;recommended_route_id:string|null}>('/api/routes/safe',{origin:location,destination});setRoutes(data.routes);setNotice(data.message);setSelected(data.recommended_route_id||data.routes[0]?.id||'')}catch(e){setError(message(e))}finally{setBusy(false)}}
 return <div className="route-workspace"><div className="panel route-planner"><div className="eyebrow">PLAN WITH CONTEXT</div><h2>Find a lower-risk route</h2><p className="muted">Compare available alternatives against terrain, rainfall, incidents and road closures.</p><form onSubmit={calculate}><div className="origin"><MapPin size={18}/><span>From selected location<strong>{location.latitude.toFixed(4)}, {location.longitude.toFixed(4)}</strong></span></div><label>Destination preset<select onChange={e=>{const [latitude,longitude]=e.target.value.split(',').map(Number);setDestination({latitude,longitude})}}><option value="25.62,91.89">Northern Shillong · demo route</option><option value="25.27,91.73">Sohra, Meghalaya</option><option value="26.1445,91.7362">Guwahati, Assam</option></select></label><Coordinates value={destination} onChange={setDestination}/><button disabled={busy} className="primary wide"><Busy busy={busy}><Navigation size={17}/>Compare routes</Busy></button></form><ErrorText error={error}/>{notice&&<p className="notice">{notice}</p>}
 {routes.map(r=><button className={`route-option ${r.id===selected?'selected':''}`} key={r.id} onClick={()=>setSelected(r.id)}><div className="split"><strong>{r.name}</strong><Badge value={r.classification}/></div><div className="route-numbers">{(r.distance_m/1000).toFixed(1)} km <span>~{Math.round(r.duration_seconds/60)} min</span><strong>{r.route_risk_score}/100</strong></div><p>{r.reasons.join('. ')}</p>{r.travel_advice&&<p className={r.route_risk_score>=75?'route-danger':r.route_risk_score>=30?'route-warning':'route-safe'}><strong>{r.travel_advice}</strong></p>}<Source item={r}/></button>)}
 {!routes.length&&<Empty title="Your route comparison appears here">Blocked roads and critical incident corridors are excluded.</Empty>}</div>
 <div><RiskMap center={location} zones={zones} incidents={incidents} routes={routes} selectedRoute={selected} large/><div className="route-disclaimer"><RouteIcon size={20}/><p>Lower-risk means based on currently available data. Mock routes use synthetic geometry and must not be used for navigation.</p></div></div></div>
}

export function ShelterModal({location,shelter,onClose,onSaved}:{location:Location;shelter?:Shelter;onClose:()=>void;onSaved:()=>void}){
 const [coords,setCoords]=useState<Location>(shelter||location),[name,setName]=useState(shelter?.name||''),[capacity,setCapacity]=useState(shelter?.capacity||50),[occupancy,setOccupancy]=useState(shelter?.current_occupancy||0),[contact,setContact]=useState(shelter?.contact||''),[district,setDistrict]=useState(shelter?.district||''),[state,setState]=useState(shelter?.state||''),[active,setActive]=useState(shelter?.active??true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api(shelter?`/api/shelters/${shelter.id}`:'/api/shelters',{method:shelter?'PATCH':'POST',body:JSON.stringify({...coords,name,capacity,current_occupancy:occupancy,contact,district,state,verified:true,active})});onSaved();onClose()}catch(e){setError(message(e))}finally{setBusy(false)}}
 return <Modal title={shelter?'Update verified shelter':'Add verified shelter'} onClose={onClose}><form onSubmit={submit}><p className="muted">Record only a shelter verified by your authorized team. Capacity, hazard coverage and route access are checked separately.</p><label>Shelter name<input required minLength={3} value={name} onChange={e=>setName(e.target.value)}/></label><Coordinates value={coords} onChange={setCoords}/><div className="form-grid"><label>Capacity<input required type="number" min={1} value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label><label>Occupancy<input required type="number" min={0} max={capacity} value={occupancy} onChange={e=>setOccupancy(Number(e.target.value))}/></label><label>District<input required minLength={2} value={district} onChange={e=>setDistrict(e.target.value)}/></label><label>State<input required minLength={2} value={state} onChange={e=>setState(e.target.value)}/></label></div><label>Contact<input required minLength={3} value={contact} onChange={e=>setContact(e.target.value)}/></label><label className="check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Currently active</label><ErrorText error={error}/><button className="primary wide" disabled={busy}><Busy busy={busy}>Save verified shelter</Busy></button></form></Modal>
}

export function RoadModal({location,onClose,onSaved}:{location:Location;onClose:()=>void;onSaved:()=>void}){
 const [coords,setCoords]=useState(location),[name,setName]=useState(''),[status,setStatus]=useState('BLOCKED'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{await post('/api/roads',{...coords,road_identifier:name,status,risk_score:status==='BLOCKED'?100:status==='CAUTION'?60:0});onSaved();onClose()}catch(e){setError(message(e))}finally{setBusy(false)}}
 return <Modal title="Update road status" onClose={onClose}><form onSubmit={submit}><label>Road identifier<input required minLength={3} value={name} onChange={e=>setName(e.target.value)} placeholder="Same identifier updates an existing road record"/></label><Coordinates value={coords} onChange={setCoords}/><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{['OPEN','CAUTION','BLOCKED'].map(s=><option key={s}>{s}</option>)}</select></label><p className="muted">A blocked road excludes route alternatives within 300 m of this location.</p><ErrorText error={error}/><button className="primary wide" disabled={busy}><Busy busy={busy}>Save road status</Busy></button></form></Modal>
}

export function PopulationView({items}:{items:Exposure[]}){return <div className="panel"><div className="notice">Exposure estimates use available population and risk-zone data. Demo populations are synthetic.</div>{!items.length?<Empty title="No exposure records available"/>:<div className="table-scroll"><table><thead><tr><th>Priority area</th><th>Risk</th><th>Estimated people</th><th>Priority score</th><th>Shelters</th><th>Source</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small>{p.district}, {p.state}</small></td><td><Badge value={p.risk_level}/></td><td>{p.estimated_exposed_population.toLocaleString()}</td><td><div className="mini-bar"><i style={{width:p.exposure_priority_score+'%'}}/></div>{p.exposure_priority_score}/100</td><td>{p.verified_shelters_nearby} available</td><td><Badge value={p.data_mode}/></td></tr>)}</tbody></table></div>}</div>}
export function DispatchView({items,onChanged,onError}:{items:Dispatch[];onChanged:()=>void;onError:(s:string)=>void}){return <div className="card-grid">{items.length?items.map(d=><article className="panel" key={d.id}><div className="split"><h3>{d.assigned_team}</h3><Badge value={d.status}/></div><Badge value={d.priority}/><p>{d.instructions}</p><p className="muted">Recorded {new Date(d.created_at).toLocaleString()}</p>{d.status==='ASSIGNED'&&<button onClick={()=>post(`/api/dispatches/${d.id}/complete`).then(onChanged).catch(e=>onError(message(e)))}>Mark completed</button>}</article>):<Empty title="No response teams dispatched">Open an incident to record a dispatch.</Empty>}</div>}
